version: '3'

services:
    db:
        image: mysql:5.7
        #command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_DATABASE: main
            MYSQL_USER: toha
            MYSQL_PASSWORD: 1234
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8002:8000
        links:
            - db
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8001:80
        links:
            - php
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
